version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./app:/app
      - ./docker/dkron.data:/dkron.data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env.local

